version: '3.8'

services:
  fastapi:
    image: fastapi_poetry_i
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fastapi_poetry_c
    ports:
      - "8000:8000"
    volumes:
      - ./src:/app/src
    env_file: .env
    environment:
      - RUNNING_IN_DOCKER=true
      - DB_HOST=mysql_c
    restart: unless-stopped
    networks:
      - app_net

networks:
  app_net:
    external: true